services:
  grampad:
    image: ghcr.io/grampadio/grampad:1.0.1
    container_name: grampad
    ports:
      - "${HOST_PORT:-3004}:${PORT:-3004}"
    env_file:
      - .env
    restart: unless-stopped
